env:
  es6: true
  browser: true

extends: "htmlacademy/es6"

rules:
  # linebreak-style: ["error", "windows"]
  semi: 2
  no-unused-vars: 1
  quotes: [2, "double", "avoid-escape"]
  block-spacing: ["error", "never"]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  object-curly-spacing: ["error", "never"]

parserOptions:
  sourceType: "module"
  ecmaVersion: 2015
